### ISSUE TITLE
Stalker doesn't work 2.

### ISSUE THREAD

**Issue by arion75** [zgemma-star/e2plugins#6]
Stalker doesn't work. There are no errors. After turning on the Stalker, it is thrown back to watching satellite channels.
I think the problem is in the dependent files. They differ with working options on ATV, HDF and PKT.
OpenPli
![oprnpli(21-50-09)](https://user-images.githubusercontent.com/59334549/101290038-06865b00-3811-11eb-8f3a-d44dcbc6b947.jpg)
ATV_HDF_PKT
![ATV_HDF_PKT(21-45-23)](https://user-images.githubusercontent.com/59334549/101290042-0ede9600-3811-11eb-910e-29a6b484e95c.jpg)

**Comment by atvcaptain** [comment]
build qt 5.9 and not 5.13 very simple fix

**Comment by Dima73** [comment]
> 
> 
> build qt 5.9 and not 5.13 very simple fix

Can I get a little more detail, please?

**Comment by 68foxboris** [comment]
I put together a plugin for gi et11000 4k(analog by drivers sf4008)-qtwebkit_5.9.8+git0+bd0657f98a-r0_et1x000.ipk.After turning on the Stalker,it is thrown back to watching satellite channels.The situation is better with the browser: it starts up, but immediately freezes.How can this be fixed?
`
2021-02-07 16:36:36+0200 [-] (1, 'ZDF Start', 'http://hbbtv.zdf.de/zdfstart/index.php', 17, 1, 0)
2021-02-07 16:36:39+0200 [-] [ActionMap] Keymap 'InfobarRedButtonActions' -> Action = 'activateRedButton'.
2021-02-07 16:36:39+0200 [-] URL http://hbbtv.zdf.de/zdfstart/index.php
2021-02-07 16:36:39+0200 [-] PMT 6100 TSID 1011 ONID 1 SSID 11110
2021-02-07 16:36:39+0200 [-] ServerFactory starting on '/tmp/.sock.browser'
2021-02-07 16:36:39+0200 [-] Starting factory <twisted.internet.protocol.ServerFactory instance at 0xb16fc3c8>
2021-02-07 16:36:39+0200 [-] [Skin] Parsing embedded skin '<embedded-in-HbbTVWindow>'.
2021-02-07 16:36:39+0200 [-] [Skin] Processing screen '<embedded-in-HbbTVWindow>', position=(0, 0), size=(1280 x 720) for module 'HbbTVWindow'.
2021-02-07 16:36:39+0200 [-] [Skin] Parsing embedded skin '<embedded-in-SimpleSummary>'.
2021-02-07 16:36:39+0200 [-] [Skin] Processing screen '<embedded-in-SimpleSummary>' from list 'HbbTVWindow_summary, SimpleSummary', position=(0, 0), size=(132 x 64) for module 'SimpleSummary'.
2021-02-07 16:36:39+0200 [-] [Screen] Showing screen '['HbbTVWindow_summary', 'SimpleSummary']'.
2021-02-07 16:36:39+0200 [-] [Screen] Showing screen 'HbbTVWindow'.
2021-02-07 16:36:47+0200 [ClientConnection,0,] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/enigma2/python/mytest.py", line 99, in runReactor
	    reactor.run(installSignalHandlers=False)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1283, in run
	    
	  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1295, in mainLoop
	    
	  File "/usr/lib/enigma2/python/e2reactor.py", line 168, in doPoll
	    
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    
	  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
	    
	  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
	    
	  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
	    
	  File "/usr/lib/enigma2/python/e2reactor.py", line 196, in _doReadOrWrite
	    
	  File "/usr/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 252, in _disconnectSelectable
	    
	  File "/usr/lib/python2.7/site-packages/twisted/internet/tcp.py", line 307, in readConnectionLost
	    
	  File "/usr/lib/python2.7/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
	    
	  File "/usr/lib/enigma2/python/Plugins/Extensions/QtHbbtv/datasocket.py", line 47, in connectionLost
	    x()
	  File "/usr/lib/enigma2/python/Plugins/Extensions/QtHbbtv/browser.py", line 72, in onBrowserClosed
	    x()
	  File "/usr/lib/enigma2/python/Plugins/Extensions/QtHbbtv/hbbtv.py", line 103, in onExit
	    file = open('/proc/stb/vmpeg/0/zorder', 'w')
	exceptions.IOError: [Errno 2] No such file or directory: '/proc/stb/vmpeg/0/zorder'
`

**Comment by 68foxboris** [comment]
Please tell me what to add to the dependency qthbbtv to make this file appear-/proc/stb/vmpeg/0/zorder.

**Comment by atvcaptain** [comment]
the addon never working with gi et11000 forget your request, better buy a zgemma box when you need this addon

**Comment by 68foxboris** [comment]
Thanks for the advice.
